### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Overbryd** [moranmathias/brod_ex#1]
Hi @moranmathias ,

really happy to see someone working on brod + elixir.
In my past project I have done so as well, and implemented a `CoordinatedGroupMember`, some `Kafka.Utils` (including to fetch lag/offsets for consumer groups).

I was about to start my own elixir + brod library, but then I found this one. And it looks very similar to what I have built for a couple of clients internally.

So my obvious question: Do you still maintain brod_ex?

I am going to fork it for now, add my own stuff and PR your with my proposals.

Happy to hear from you,

Kind regards,

Lukas

**Comment by moranmathias** [comment]
Hi @Overbryd i'm happy to hear that someone else will use brod_ex. The project is alive and in use working pretty fine. 
I will happily receive your proposals!

**Comment by Overbryd** [comment]
Ok. My problem for now is to get your configuration working following the README. The README seems to be copied over from brod and adapter to the library you have created.

I kind of like the idea, similar to Ecto repositories, to have one module for each kafka cluster.
So but, then I do not quite understand, and maybe this is missing, how to tie one `MyApp.Brod` to a specific client configured in the application configuration.

So given the following configuration/setup, I was not able to get a few things, that are advertised in the README to work.

```elixir
# config/config.exs
use Mix.Config

config :example, :brod_ex, clients: [
  {Example.Brod, [
    endpoints: ["localhost:9092"],
    auto_start_producers: true,
    default_producer_config: []
  ]}
]
```

```elixir
# lib/example.ex
defmodule Example do
  use Application

  def start(_type, _args) do
    children = [
      {Example.Brod, []}
    ]

    opts = [strategy: :one_for_one, name: Example.Supervisor]
    Supervisor.start_link(children, opts)
  end

end
```

```elixir
# lib/example/brod.ex
defmodule Example.Brod do
  use BrodEx, otp_app: :example
end
```

If I now call `Example.Brod.produce_sync/5` it is not implemented.
Ok, so I think it must be `BrodEx.produce_sync/5` (where you have to specify a client).

So either of them makes sense, but I do not think it is necessary to have a "client" module, that just calls into `:brod.start(:normal, [])`. Something that might only work for one "client" module.

So to have multi-cluster support (something I do not need), I think one "client" module like `Example.Brod` should specifically start a given client configuration, instead of brod.

As far as I understand brod, it is its very own application and just needs to be started. That means, if `BrodEx` lists `:brod` in its extra applications, I think we would be fine of having `brod` started.

Then we could supervise individual clients.

Anyways, thats a design decision that I am not sure why it is there and what it is for, and where you like to go with this.

**Comment by Overbryd** [comment]
So here is my first PR: https://github.com/moranmathias/brod_ex/pull/2

I am closing this issue. Thanks for stopping by, good to know another human being is on the other end, interested to read my PRs.
